# Generated by Django 5.0.3 on 2024-03-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('NS', 'новость'), ('AT', 'статья')], default='NS', max_length=2),
        ),
    ]
